class Routes {
  static const String imagePackage = "imagePackage",
      playerVideo = "playerVideo",
      pickerImage = "pickerImage",
      pickerFile = "pickerFile",
      launchUrl = "launchUrl",
      cachedNetwork = "cachedNetwork",
      locationPage = "locationPage",
      loadingCustom = "loadingCustom",
      infoPackages = "infoPackages",
      storeFile = "storeFile",
      intlPackage = "intlPackage",
      tweenAnimation = "tweenAnimation",
      heroAnimation = "heroAnimation",
      animatedOpacityTask = "animatedOpacityTask",
      localAuthTask = "localAuthTask",
      sliverTask = "sliverTask",
      shimmerTask = "shimmerTask",
      phoneScreen = "phoneScreen",
      heroNavigation = "heroNavigation",
      storedData = "storedData",
      imageStore = "imageStore",
      pinCodeScreen = "pinCodeScreen",
      formScreen = "formScreen";
}
